// Donc ici, c'est la page qui permettra d'afficher les recettes, en fonction de l'api...
// Une page, en fonction de l'id de la recette qu'on choisit...

export default function RecipeId() {
    return 
}
